/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando's
 */
public class EmployeAssignTask extends javax.swing.JPanel {

    /**
     * Creates new form EmployeAssignTask
     */
    public EmployeAssignTask() {
        initComponents();
        jLabel1.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmpID = new javax.swing.JTextField();
        txtEmpName = new javax.swing.JTextField();
        txtJobROle = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        dateSelect = new com.toedter.calendar.JSpinnerDateEditor();
        btnAssign = new javax.swing.JButton();
        btnSendMail = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Assign Task");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Employee ID :");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Employee Name :");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Job Role :");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Assign Date & Time:");

        txtEmpID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        txtEmpName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        txtJobROle.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        btnSearch.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/search x30.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        dateSelect.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        btnAssign.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAssign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/check in.png"))); // NOI18N
        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnSendMail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSendMail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/img/email.png"))); // NOI18N
        btnSendMail.setText("Send Mail");
        btnSendMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMailActionPerformed(evt);
            }
        });

        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Description: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEmpID)
                                    .addComponent(txtEmpName)
                                    .addComponent(txtJobROle)
                                    .addComponent(dateSelect, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch)))
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnAssign)
                .addGap(18, 18, 18)
                .addComponent(btnSendMail)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJobROle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dateSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssign)
                    .addComponent(btnSendMail))
                .addGap(49, 49, 49))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        Connection con = DatabaseLayer.mycon();
        PreparedStatement pst = null;
        ResultSet rs = null;
        
        String empID= txtEmpID.getText();
        
        try {
        
        String sql = "SELECT Name, Job_Role FROM employees WHERE employee_id = ?";

        
        pst = con.prepareStatement(sql);
        pst.setString(1, empID);

        rs = pst.executeQuery();

        if (rs.next()) {
            
            txtEmpName.setText(rs.getString("Name"));
            txtJobROle.setText(rs.getString("Job_Role"));
        } else {
            JOptionPane.showMessageDialog(null, "Employee not found!");
        }

        } catch (SQLException ex) {
             JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
        } finally {
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (con != null) con.close();
        } catch (SQLException ex) {
            ex.printStackTrace(); 
            JOptionPane.showMessageDialog(null, "Error closing database resources: " + ex.getMessage());
        }
    }
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        
        Date fullDateTime = (Date) dateSelect.getValue();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");

        String dateOnly = dateFormat.format(fullDateTime);
        String timeOnly = timeFormat.format(fullDateTime);
        
        
        String empID=txtEmpID.getText();
        String jobRole=txtJobROle.getText();
        String description=txtDescription.getText();
        
        try {
            Connection con = DatabaseLayer.mycon(); 
            PreparedStatement pst=null;

            String sql = "INSERT INTO employeetasks (employee_id, task_description, dutyDate, dutyTime) VALUES (?, ?, ?, ?)";
            pst = con.prepareStatement(sql);

            pst.setString(1, empID);        
            pst.setString(2, description);  
            pst.setString(3, dateOnly);     
            pst.setString(4, timeOnly);  

            int rowsInserted = pst.executeUpdate();

            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(null, "Task assigned successfully!");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to assign task.");
            }

            } catch (SQLException ex) {
                 ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage());
            } 
   
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnSendMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMailActionPerformed
        // TODO add your handling code here:
        try {
        Connection con = DatabaseLayer.mycon(); 
        PreparedStatement pstEmail = null;
        PreparedStatement pstTask = null;

        String empID = txtEmpID.getText();

        // Get employee email
        String getEmailSQL = "SELECT Email FROM employees WHERE employee_id = ?";
        pstEmail = con.prepareStatement(getEmailSQL);
        pstEmail.setString(1, empID);
        ResultSet rsEmail = pstEmail.executeQuery();

        if (rsEmail.next()) {
            String toEmail = rsEmail.getString("Email");

            // Get latest task for this employee
            String getTaskSQL = "SELECT task_description, dutyDate, dutyTime FROM employeetasks WHERE employee_id = ? ORDER BY task_id DESC LIMIT 1";
            pstTask = con.prepareStatement(getTaskSQL);
            pstTask.setString(1, empID);
            ResultSet rsTask = pstTask.executeQuery();

            if (rsTask.next()) {
                String description = rsTask.getString("task_description");
                String dateOnly = rsTask.getString("dutyDate");
                String timeOnly = rsTask.getString("dutyTime");

                // Email content
                String subject = "📌 New Task Assigned to You";
                String body = "Dear Employee,\n\n" +
                              "You have been assigned a new task with the following details:\n\n" +
                              "📝 Description: " + description + "\n" +
                              "📅 Date: " + dateOnly + "\n" +
                              "⏰ Time: " + timeOnly + "\n\n" +
                              "Please make sure to complete it on time.\n\n" +
                              "Best Regards,\n" +
                              "Panorama Hotel Management";

                // Send email
                Send_Email_Handler.sendEmail(toEmail, subject, body);
            } else {
                JOptionPane.showMessageDialog(null, "No task found for the selected employee.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Employee email not found.");
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Database error: " + e.getMessage());
    }
    
    }//GEN-LAST:event_btnSendMailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSendMail;
    private com.toedter.calendar.JSpinnerDateEditor dateSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtEmpID;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtJobROle;
    // End of variables declaration//GEN-END:variables

    
}
