/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author THARINDU
 */
public class RoomReservationUI extends javax.swing.JFrame {

    /**
     * Creates new form RoomRes
     */
    
   public RoomReservationUI() {
    initComponents();
    setTitle("Room Reservation");
    setLocationRelativeTo(null);

    getContentPane().setLayout(new BorderLayout()); // 🔥 IMPORTANT

    buildCalendar();
}
    
    private void reserveRoom(int roomNo, int day, JButton button) {

    int confirm = JOptionPane.showConfirmDialog(this,
            "Reserve Room " + roomNo + " on Day " + day + "?");

    if (confirm == JOptionPane.YES_OPTION) {

        button.setBackground(Color.RED); // Mark as booked
        button.setToolTipText("Booked");
    }
}
    
    private void buildCalendar() {

    int daysInMonth = 28;   // You can calculate dynamically
    int totalRooms = 5;     // Get from database later

    JPanel panel = new JPanel();
    panel.setLayout(new GridLayout(totalRooms + 1, daysInMonth + 1));

    // Top-left empty cell
    panel.add(new JLabel("Room/Day", SwingConstants.CENTER));

    // Add Day Headers
    for (int day = 1; day <= daysInMonth; day++) {
        JLabel lblDay = new JLabel(String.valueOf(day), SwingConstants.CENTER);
        lblDay.setFont(new Font("Arial", Font.BOLD, 14));
        panel.add(lblDay);
    }

    // Add Rooms + Buttons
    for (int room = 1; room <= totalRooms; room++) {

        int roomNumber = 100 + room;

        panel.add(new JLabel("Room " + roomNumber));

        for (int day = 1; day <= daysInMonth; day++) {

            JButton btn = new JButton();
            btn.setBackground(Color.GREEN); // Available

            int selectedDay = day;

            btn.addActionListener(e -> {
                reserveRoom(roomNumber, selectedDay, btn);
            });

            panel.add(btn);
        }
    }

    getContentPane().add(new JScrollPane(panel), BorderLayout.CENTER);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 967, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 632, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomReservationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomReservationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomReservationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomReservationUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RoomReservationUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
