/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.alee.laf.WebLookAndFeel;
import com.alee.managers.language.LanguageManager;
import control.CommonControl;
import control.DatabaseLayer;
import control.Options;
import control.PrintStatus;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author ASUS
 */
public class MainMenu extends javax.swing.JFrame {

    private static int userPrivilege;
    private static String username;
    private Timer clockTimer;

    /**
     * Creates new form MainMenu
     */
    public MainMenu(int userPrivilege, String userName) {
        this.userPrivilege = userPrivilege;
        this.username = userName;
        initComponents();
        setLocationRelativeTo(null);
        setDateAndTime();
        loadMonthsToCombo();
        lblUser.setText(username);
        setUI();
        setWIndowMoveble();
    }

    private void setWIndowMoveble() {
        lblTitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblTitileMouseDragged(evt);
            }
        });
        lblTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTitileMousePressed(evt);
            }
        });
    }

    private void lblTitileMouseDragged(java.awt.event.MouseEvent evt) {
        this.setLocation(evt.getXOnScreen() - Options.selectedWindowXPosition, evt.getYOnScreen());
    }

    private void lblTitileMousePressed(java.awt.event.MouseEvent evt) {
        Options.selectedWindowXPosition = evt.getX();
    }

    private void setDateAndTime() {
        clockTimer = new Timer(1000, e -> {
            SimpleDateFormat sdf
                    = new SimpleDateFormat("yyyy-MM-dd | EEEE | hh:mm:ss a", Locale.getDefault());
            String currentDateAndTime = sdf.format(new Date());
            lblDateAndTime.setText(currentDateAndTime);
        });
        clockTimer.start();
    }

    private void setUI() {
        if (userPrivilege == Options.USER_PRIVILEGE) {
            mainPanel.remove(reportPanel);
            mainPanel.remove(btnInventory);
            mainPanel.remove(btnSettings);
        }
    }

    private void updateLoginDetail(String username) {
        // SQL query to update logout timestamp for the latest login of the user
        String query = "UPDATE login_detail "
                + "SET login_detail_logout_date_time = CURRENT_TIMESTAMP "
                + "WHERE login_detail_username = ? "
                + "ORDER BY login_detail_id DESC LIMIT 1";

        try (Connection con = DatabaseLayer.getConnection();
                PreparedStatement pst = con.prepareStatement(query)) {

            pst.setString(1, username);  // set username
            pst.executeUpdate();  // execute update

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void loadMonthsToCombo() {
        comboMonth.removeAllItems();

        String[] months = {
            "January", "February", "March", "April", "May", "June",
            "July", "August", "September", "October", "November", "December"
        };

        for (String month : months) {
            comboMonth.addItem(month);
        }

        int currentMonthIndex = java.util.Calendar.getInstance().get(java.util.Calendar.MONTH);
        comboMonth.setSelectedIndex(currentMonthIndex);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        lblMinimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblAbout = new javax.swing.JLabel();
        lblDateAndTime = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCheckOut = new com.alee.laf.button.WebButton();
        btnAddBooking = new com.alee.laf.button.WebButton();
        btnViewBooking = new com.alee.laf.button.WebButton();
        btnHistory = new com.alee.laf.button.WebButton();
        reportPanel = new javax.swing.JPanel();
        webButton5 = new com.alee.laf.button.WebButton();
        btnMonthlyBookings = new com.alee.laf.button.WebButton();
        webButton7 = new com.alee.laf.button.WebButton();
        lblTitle1 = new javax.swing.JLabel();
        webButton8 = new com.alee.laf.button.WebButton();
        comboMonth = new com.alee.laf.combobox.WebComboBox();
        btnInventory = new com.alee.laf.button.WebButton();
        btnRooms = new com.alee.laf.button.WebButton();
        btnSettings = new com.alee.laf.button.WebButton();
        lblCurrency = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel-Management-System | Srinill Beach Resort");
        setMinimumSize(new java.awt.Dimension(1366, 738));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 738));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(0, 51, 102));
        mainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimize.setBackground(new java.awt.Color(0, 153, 153));
        lblMinimize.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        lblMinimize.setForeground(new java.awt.Color(255, 255, 255));
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setText("__");
        lblMinimize.setOpaque(true);
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
        });
        mainPanel.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1295, 0, 20, 17));

        lblClose.setBackground(new java.awt.Color(204, 0, 0));
        lblClose.setFont(new java.awt.Font("Ubuntu", 1, 10)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 255, 255));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        mainPanel.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 0, 50, 17));

        lblTitle.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("  Main Menu");
        lblTitle.setOpaque(true);
        mainPanel.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 20));

        jPanel3.setBackground(new java.awt.Color(0, 51, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAbout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAbout.setForeground(new java.awt.Color(255, 255, 255));
        lblAbout.setText("Software by Meshan Miranda | 0764315233 | ID : 3004867");
        jPanel3.add(lblAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, -1, 590, 40));

        lblDateAndTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDateAndTime.setForeground(new java.awt.Color(255, 255, 255));
        lblDateAndTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDateAndTime.setText("Date And Time");
        jPanel3.add(lblDateAndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, -1, 510, 40));

        mainPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 679, 1330, 40));

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUser.setText("Admin");
        jPanel2.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1176, -1, 140, 90));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SRINILL BEACH RESORT");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, -1, 500, 90));

        mainPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1330, -1));

        btnCheckOut.setText("CHECK OUT");
        btnCheckOut.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });
        mainPanel.add(btnCheckOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 250, 60));

        btnAddBooking.setText("ADD BOOKING");
        btnAddBooking.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnAddBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookingActionPerformed(evt);
            }
        });
        mainPanel.add(btnAddBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 250, 60));

        btnViewBooking.setText("VIEW BOOKING");
        btnViewBooking.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnViewBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBookingActionPerformed(evt);
            }
        });
        mainPanel.add(btnViewBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 250, 60));

        btnHistory.setText("HISTORY");
        btnHistory.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        mainPanel.add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 250, 60));

        reportPanel.setBackground(new java.awt.Color(0, 51, 102));
        reportPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        reportPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        webButton5.setText("MONTHLY PAYMENTS");
        webButton5.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        webButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton5ActionPerformed(evt);
            }
        });
        reportPanel.add(webButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 320, 50));

        btnMonthlyBookings.setText("MONTHLY BOOKINGS");
        btnMonthlyBookings.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btnMonthlyBookings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthlyBookingsActionPerformed(evt);
            }
        });
        reportPanel.add(btnMonthlyBookings, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 320, 50));

        webButton7.setText("MONTHLY PAYMENTS - CARD");
        webButton7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        webButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton7ActionPerformed(evt);
            }
        });
        reportPanel.add(webButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 320, 50));

        lblTitle1.setBackground(new java.awt.Color(0, 0, 0));
        lblTitle1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Reports");
        lblTitle1.setOpaque(true);
        reportPanel.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 620, 20));

        webButton8.setText("MONTHLY PAYMENTS - CASH");
        webButton8.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        webButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton8ActionPerformed(evt);
            }
        });
        reportPanel.add(webButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 320, 50));

        comboMonth.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        comboMonth.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboMonthPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        reportPanel.add(comboMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 270, 50));

        mainPanel.add(reportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 640, 500));

        btnInventory.setText("INVENTORY");
        btnInventory.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInventoryActionPerformed(evt);
            }
        });
        mainPanel.add(btnInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 250, 60));

        btnRooms.setText("ROOMS");
        btnRooms.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnRooms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomsActionPerformed(evt);
            }
        });
        mainPanel.add(btnRooms, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 250, 60));

        btnSettings.setText("SETTINGS");
        btnSettings.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        btnSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingsActionPerformed(evt);
            }
        });
        mainPanel.add(btnSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 250, 60));

        lblCurrency.setBackground(new java.awt.Color(0, 51, 102));
        lblCurrency.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblCurrency.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mainPanel.add(lblCurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 520, 100));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1367, 738));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        int choice = JOptionPane.showConfirmDialog(
                null,
                "Are you sure you want to exit this system?",
                "Confirm Exit",
                JOptionPane.YES_NO_OPTION
        );

        // If user clicked YES
        if (choice == JOptionPane.YES_OPTION) {
            // Update logout time
            updateLoginDetail(username);

            // Close the window
            this.dispose();
        }
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnAddBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookingActionPerformed
        new AddBooking(null, "").setVisible(true);
    }//GEN-LAST:event_btnAddBookingActionPerformed

    private void btnViewBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBookingActionPerformed
        new ViewBooking().setVisible(true);
    }//GEN-LAST:event_btnViewBookingActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        new CheckOut().setVisible(true);
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        new BookingHistory().setVisible(true);
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void webButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton5ActionPerformed
        try {
            Map<String, Object> params = new HashMap<>();
            int selectedMonth = comboMonth.getSelectedIndex() + 1;
            int currentYear = java.time.LocalDate.now().getYear();

            LocalDate firstDate = LocalDate.of(currentYear, selectedMonth, 1);
            LocalDate lastDate = firstDate.with(java.time.temporal.TemporalAdjusters.lastDayOfMonth());

            params.put("fromDate", java.sql.Date.valueOf(firstDate));
            params.put("toDate", java.sql.Date.valueOf(lastDate));
            params.put("month", currentYear + " / " + comboMonth.getSelectedItem());
            CommonControl.printReport("monthly_payments", params, PrintStatus.WITH_VIEW);
        } catch (JRException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_webButton5ActionPerformed

    private void btnMonthlyBookingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonthlyBookingsActionPerformed
        try {
            Map<String, Object> params = new HashMap<>();
            int selectedMonth = comboMonth.getSelectedIndex() + 1;
            int currentYear = java.time.LocalDate.now().getYear();

            LocalDate firstDate = LocalDate.of(currentYear, selectedMonth, 1);
            LocalDate lastDate = firstDate.with(java.time.temporal.TemporalAdjusters.lastDayOfMonth());

            params.put("fromDate", java.sql.Date.valueOf(firstDate));
            params.put("toDate", java.sql.Date.valueOf(lastDate));
            params.put("month", currentYear + " / " + comboMonth.getSelectedItem());
            CommonControl.printReport("monthly_bookings", params, PrintStatus.WITH_VIEW);
        } catch (JRException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMonthlyBookingsActionPerformed

    private void webButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_webButton7ActionPerformed

    private void webButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_webButton8ActionPerformed

    private void btnInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInventoryActionPerformed
        JOptionPane.showMessageDialog(this, "Please Contact Your Admin!", "Access Denied", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnInventoryActionPerformed

    private void btnRoomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomsActionPerformed
        new RoomManagement().setVisible(true);
    }//GEN-LAST:event_btnRoomsActionPerformed

    private void btnSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingsActionPerformed
        JOptionPane.showMessageDialog(this, "Please Contact Your Admin!", "Access Denied", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnSettingsActionPerformed

    private void comboMonthPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboMonthPopupMenuWillBecomeInvisible

    }//GEN-LAST:event_comboMonthPopupMenuWillBecomeInvisible

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu(1, null).setVisible(true);
                WebLookAndFeel.install();
                LanguageManager.initialize();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton btnAddBooking;
    private com.alee.laf.button.WebButton btnCheckOut;
    private com.alee.laf.button.WebButton btnHistory;
    private com.alee.laf.button.WebButton btnInventory;
    private com.alee.laf.button.WebButton btnMonthlyBookings;
    private com.alee.laf.button.WebButton btnRooms;
    private com.alee.laf.button.WebButton btnSettings;
    private com.alee.laf.button.WebButton btnViewBooking;
    private com.alee.laf.combobox.WebComboBox comboMonth;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblClose;
    private javax.swing.JPanel lblCurrency;
    private javax.swing.JLabel lblDateAndTime;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel reportPanel;
    private com.alee.laf.button.WebButton webButton5;
    private com.alee.laf.button.WebButton webButton7;
    private com.alee.laf.button.WebButton webButton8;
    // End of variables declaration//GEN-END:variables
}
